---
title: "model selection for hourly SSF"
author: "Jessalyn Ayars"
date: "2022-08-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(glmmTMB)
source(here("code", "misc_functions.R"))
```


## Data
```{r}
ssf.hr.data <- read_csv(here("data-public", "ssf_hr_final.csv")) %>%
  mutate(id = str_c(Territory, ".", Year)) %>%
  mutate(step.id.id = str_c(id, ".", step_id_))
```

## Checks
- correlated > 0.6: cc and ch, ch and s10z, s10z and sdq, sdq and sq, also cc and s10z using pearson
```{r}
pairs(ssf.hr.data[c(5, 21:27)], lower.panel = panel.pearson)

# random effects structure 
table(ssf.hr.data$Territory, ssf.hr.data$case_)
table(ssf.hr.data$Year, ssf.hr.data$case_)
table(ssf.hr.data$id, ssf.hr.data$case_) # nothing obviously problematic, a few small groups
```

## Models
```{r}
ssf.hr.cc <- glmmTMB(case_ ~ (1|step.id.id) + (1|id) + (0 + cc.30.scaled|id) + (0 + I(cc.30.scaled^2)|id) + cc.30.scaled + I(cc.30.scaled^2), 
                       family=poisson, REML = T, data= ssf.hr.data, doFit=FALSE) 
ssf.hr.cc$parameters$theta[1] = log(1e3) 
ssf.hr.cc$mapArg = list(theta=factor(c(NA, 1, 2, 3))) 
ssf.hr.cc = glmmTMB:::fitTMB(ssf.hr.cc) 
summary(ssf.hr.cc)  
cc.30 <- coef(ssf.hr.cc)$cond$id$cc.30.scaled
cc.30.2 <- coef(ssf.hr.cc)$cond$id[3]

ssf.hr.ch <- glmmTMB(case_ ~ (1|step.id.id) + (1|id) + (0 + ch.30.scaled|id) + (0 + I(ch.30.scaled^2)|id) + ch.30.scaled + I(ch.30.scaled^2), 
                       family=poisson, REML = T, data= ssf.hr.data, doFit=FALSE) 
ssf.hr.ch$parameters$theta[1] = log(1e3) 
ssf.hr.ch$mapArg = list(theta=factor(c(NA, 1, 2, 3))) 
ssf.hr.ch = glmmTMB:::fitTMB(ssf.hr.ch) 
summary(ssf.hr.ch)  
ch.30 <- coef(ssf.hr.ch)$cond$id$ch.30.scaled
ch.30.2 <- coef(ssf.hr.ch)$cond$id[3]


ssf.hr.lfd <- glmmTMB(case_ ~ (1|step.id.id) + (1|id) + (0 + lfd.120.scaled|id) + lfd.120.scaled, 
                       family=poisson, REML = T, data= ssf.hr.data, doFit=FALSE) 
ssf.hr.lfd$parameters$theta[1] = log(1e3) 
ssf.hr.lfd$mapArg = list(theta=factor(c(NA, 1, 2))) 
ssf.hr.lfd = glmmTMB:::fitTMB(ssf.hr.lfd) 
summary(ssf.hr.lfd)  
lfd.120 <- coef(ssf.hr.lfd)$cond$id$lfd.120.scaled

ssf.hr.s10z <- glmmTMB(case_ ~ (1|step.id.id) + (1|id) + (0 + s10z.60.scaled|id) + s10z.60.scaled, 
                       family=poisson, REML = T, data= ssf.hr.data, doFit=FALSE) 
ssf.hr.s10z$parameters$theta[1] = log(1e3) 
ssf.hr.s10z$mapArg = list(theta=factor(c(NA, 1, 2))) 
ssf.hr.s10z = glmmTMB:::fitTMB(ssf.hr.s10z) 
summary(ssf.hr.s10z)  
s10z.60 <- coef(ssf.hr.s10z)$cond$id$s10z.60.scaled

ssf.hr.sci <- glmmTMB(case_ ~ (1|step.id.id) + (1|id) + (0 + sci.60.scaled|id) + sci.60.scaled, 
                       family=poisson, REML = T, data= ssf.hr.data, doFit=FALSE) 
ssf.hr.sci$parameters$theta[1] = log(1e3) 
ssf.hr.sci$mapArg = list(theta=factor(c(NA, 1, 2))) 
ssf.hr.sci = glmmTMB:::fitTMB(ssf.hr.sci) 
summary(ssf.hr.sci)  
sci.60 <- coef(ssf.hr.sci)$cond$id$sci.60.scaled

ssf.hr.sdq <- glmmTMB(case_ ~ (1|step.id.id) + (1|id) + (0 + sdq.30.scaled|id) + sdq.30.scaled, 
                       family=poisson, REML = T, data= ssf.hr.data, doFit=FALSE) 
ssf.hr.sdq$parameters$theta[1] = log(1e3) 
ssf.hr.sdq$mapArg = list(theta=factor(c(NA, 1, 2))) 
ssf.hr.sdq = glmmTMB:::fitTMB(ssf.hr.sdq) 
summary(ssf.hr.sdq)  
sdq.30 <- coef(ssf.hr.sdq)$cond$id$sdq.30.scaled

ssf.hr.sf <- glmmTMB(case_ ~ (1|step.id.id) + (1|id) + (0 + sf.30.scaled|id) + sf.30.scaled, 
                       family=poisson, REML = T, data= ssf.hr.data, doFit=FALSE) 
ssf.hr.sf$parameters$theta[1] = log(1e3) 
ssf.hr.sf$mapArg = list(theta=factor(c(NA, 1, 2))) 
ssf.hr.sf = glmmTMB:::fitTMB(ssf.hr.sf) 
summary(ssf.hr.sf) 
sf.30 <- coef(ssf.hr.sf)$cond$id$sf.30.scaled


ssf.hr.sq <- glmmTMB(case_ ~ (1|step.id.id) + (1|id) + (0 + sq.30.scaled|id) + sq.30.scaled, 
                       family=poisson, REML = T, data= ssf.hr.data, doFit=FALSE) 
ssf.hr.sq$parameters$theta[1] = log(1e3) 
ssf.hr.sq$mapArg = list(theta=factor(c(NA, 1, 2))) 
ssf.hr.sq = glmmTMB:::fitTMB(ssf.hr.sq) 
summary(ssf.hr.sq)  
sq.30 <- coef(ssf.hr.sq)$cond$id$sq.30.scaled
```

## Output
```{r}
ids <- ssf.hr.data %>%
  distinct(id) %>%
  arrange(id)

output <- cbind(ids, cc.30, cc.30.2, ch.30, ch.30.2, lfd.120, s10z.60, sci.60, sdq.30, sf.30, sq.30)  %>%
  rename(cc.30.sq = "I(cc.30.scaled^2)", ch.30.sq = "I(ch.30.scaled^2)")

write_csv(output, here("data-public", "ssf_hr_results.csv"))
```

